version: '1.0'
services:
  db:
    container_name: timemanager_db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: timemanager_dev
    ports:
      - "5442:5432"
    volumes:
      - ./database_timemanager:/var/lib/postgresql/data

#psql -p 5442 -h 127.0.0.1 -U postgres

